version: '3.9'
services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=konstanta
    volumes:
      - ./konstanta.sql:/docker-entrypoint-initdb.d/konstanta.sql
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=konstanta
      - DB_SSL=disable
      - DB_PASSWORD=123456
      - PORT=:8080
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/main"]
